In [1]:
import numpy as np
import pandas as pd

In [10]:
df = pd.read_csv("./climate2020.csv")
df

,ObsTime,StnPres,SeaPres,StnPresMax,StnPresMaxTime,StnPresMin,StnPresMinTime,Temperature,T Max,T Max Time,...,Precp1DayMax,Precp1DayMaxTime,RH,EvapA,SunShine,GloblRad,UVI Max Mean,UVI Max,UVI Max Time,Cloud Amount
0,1,1008.7,1018.9,1017.7,2020/1/1 09:33,999.6,2020/1/26 13:39,18.0,29.0,2020/1/23 12:58,...,20.0,2020/1/26 00:00,76,89.0,225.1,418.05,...,...,...,3.8
1,2,1010.5,1020.6,1017.8,2020/2/21 09:02,1001.7,2020/2/15 14:34,19.0,30.2,2020/2/26 12:12,...,2.5,2020/2/15 00:00,72,82.0,212.5,446.52,...,...,...,4.0
2,3,1005.3,1015.3,1011.6,2020/3/16 08:59,995.5,2020/3/9 14:36,22.3,33.2,2020/3/26 13:47,...,23.5,2020/3/10 00:00,70,105.6,178.0,480.35,...,...,...,6.4
3,4,1005.7,1015.7,1010.9,2020/4/2 09:51,1000.6,2020/4/19 16:45,22.2,32.8,2020/4/19 12:57,...,20.0,2020/4/2 00:00,70,100.7,154.5,493.50,...,...,...,6.4
4,5,999.4,1009.2,1005.0,2020/5/1 08:49,992.7,2020/5/17 15:52,27.5,36.9,2020/5/10 12:16,...,61.0,2020/5/22 00:00,75,121.2,167.2,522.51,...,...,...,6.7
5,6,999.1,1008.8,1004.7,2020/6/15 00:04,994.8,2020/6/12 16:17,29.1,35.1,2020/6/29 14:10,...,99.0,2020/6/14 00:00,70,121.8,211.9,609.28,...,...,...,5.4
6,7,998.7,1008.3,1003.0,2020/7/21 09:11,993.8,2020/7/14 15:43,29.6,36.3,2020/7/31 13:00,...,28.0,2020/7/2 00:00,74,137.2,215.1,614.72,...,...,...,5.9
7,8,997.5,1007.2,1006.0,2020/8/12 21:54,991.6,2020/8/25 15:04,28.5,35.2,2020/8/25 14:05,...,70.0,2020/8/3 00:00,75,112.6,174.5,526.22,...,...,...,6.3
8,9,999.5,1009.2,1005.1,2020/9/19 08:55,991.9,2020/9/1 03:36,28.1,35.1,2020/9/7 13:35,...,54.5,2020/9/13 00:00,71,111.5,198.6,512.50,...,...,...,5.5
9,10,1002.0,1011.8,1008.0,2020/10/29 08:40,995.5,2020/10/21 14:44,26.1,34.8,2020/10/4 13:28,...,0.0,2020/10/1 00:00,69,132.4,220.1,506.06,...,...,...,5.0
10,11,1005.9,1015.8,1011.0,2020/11/28 09:21,998.4,2020/11/6 15:30,23.9,33.7,2020/11/21 13:38,...,3.0,2020/11/13 00:00,72,91.3,182.9,376.24,...,...,...,4.9
11,12,1007.3,1017.4,1015.8,2020/12/31 09:37,1000.7,2020/12/28 15:16,19.5,28.5,2020/12/28 14:25,...,28.5,2020/12/9 00:00,77,81.4,156.2,338.25,...,...,...,6.6

In [11]:
df.head()

,ObsTime,StnPres,SeaPres,StnPresMax,StnPresMaxTime,StnPresMin,StnPresMinTime,Temperature,T Max,T Max Time,...,Precp1DayMax,Precp1DayMaxTime,RH,EvapA,SunShine,GloblRad,UVI Max Mean,UVI Max,UVI Max Time,Cloud Amount
0,1,1008.7,1018.9,1017.7,2020/1/1 09:33,999.6,2020/1/26 13:39,18.0,29.0,2020/1/23 12:58,...,20.0,2020/1/26 00:00,76,89.0,225.1,418.05,...,...,...,3.8
1,2,1010.5,1020.6,1017.8,2020/2/21 09:02,1001.7,2020/2/15 14:34,19.0,30.2,2020/2/26 12:12,...,2.5,2020/2/15 00:00,72,82.0,212.5,446.52,...,...,...,4.0
2,3,1005.3,1015.3,1011.6,2020/3/16 08:59,995.5,2020/3/9 14:36,22.3,33.2,2020/3/26 13:47,...,23.5,2020/3/10 00:00,70,105.6,178.0,480.35,...,...,...,6.4
3,4,1005.7,1015.7,1010.9,2020/4/2 09:51,1000.6,2020/4/19 16:45,22.2,32.8,2020/4/19 12:57,...,20.0,2020/4/2 00:00,70,100.7,154.5,493.50,...,...,...,6.4
4,5,999.4,1009.2,1005.0,2020/5/1 08:49,992.7,2020/5/17 15:52,27.5,36.9,2020/5/10 12:16,...,61.0,2020/5/22 00:00,75,121.2,167.2,522.51,...,...,...,6.7

In [12]:
df.shape

(12, 35)

In [13]:
df.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 35 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ObsTime           12 non-null     int64
 1   StnPres           12 non-null     float64
 2   SeaPres           12 non-null     float64
 3   StnPresMax        12 non-null     float64
 4   StnPresMaxTime    12 non-null     object
 5   StnPresMin        12 non-null     float64
 6   StnPresMinTime    12 non-null     object
 7   Temperature       12 non-null     float64
 8   T Max             12 non-null     float64
 9   T Max Time        12 non-null     object
 10  T Min             12 non-null     float64
 11  T Min Time        12 non-null     object
 12  Td dew point      12 non-null     float64
 13  WS                12 non-null     float64
 14  WD                12 non-null     int64
 15  WSGust            12 non-null     float64
 16  WDGust            12 non-null     int64
 17  WGustTime         12 non-null     object
 18  Precp             12 non-null     object
 19  PrecpHour         12 non-null     float64
 20  PrecpDay          12 non-null     int64
 21  PrecpMax10        12 non-null     object
 22  PrecpMax10Time    12 non-null     object
 23  PrecpMax60        12 non-null     float64
 24  PrecpMax60Time    12 non-null     object
 25  Precp1DayMax      12 non-null     float64
 26  Precp1DayMaxTime  12 non-null     object
 27  RH                12 non-null     int64
 28  EvapA             12 non-null     float64
 29  SunShine          12 non-null     float64
 30  GloblRad          12 non-null     float64
 31  UVI Max Mean      12 non-null     object
 32  UVI Max           12 non-null     object
 33  UVI Max Time      12 non-null     object
 34  Cloud Amount      12 non-null     float64
dtypes: float64(17), int64(5), object(13)
memory usage: 12.4 KB

In [16]:
for dtype in ['float64','int64','object']:
    selected = df.select_dtypes(include=[dtype])
    mean_usage_b = selected.memory_usage(deep=True).mean()
    mean_usage_mb = mean_usage_b / 1024**2 
    print(f'平均記憶體占用-{dtype}: {mean_usage_mb} MB')

平均記憶體占用-float64: 9.324815538194444e-05 MB
平均記憶體占用-int64: 9.663899739583333e-05 MB
平均記憶體占用-object: 0.0007230894906180245 MB

In [17]:
int_types = ['uint8','int8','int16','int32','int64',]
for it in int_types:
  print(np.iinfo(it)) # show max num

Machine parameters for uint8
---------------------------------------------------------------
min = 0
max = 255
---------------------------------------------------------------

Machine parameters for int8
---------------------------------------------------------------
min = -128
max = 127
---------------------------------------------------------------

Machine parameters for int16
---------------------------------------------------------------
min = -32768
max = 32767
---------------------------------------------------------------

Machine parameters for int32
---------------------------------------------------------------
min = -2147483648
max = 2147483647
---------------------------------------------------------------

Machine parameters for int64
---------------------------------------------------------------
min = -9223372036854775808
max = 9223372036854775807
---------------------------------------------------------------

In [31]:
def mean_usage(pandas_obj):
    if isinstance(pandas_obj,pd.DataFrame):
      usage_b = pandas_obj.memory_usage(deep=True).sum()
    else:
      usage_b = pandas_obj.memory_usage(deep=True)
    usage_mb = usage_b / 1024**2
    return '{:.2f} MB'.format(usage_mb)
df_int = df.select_dtypes(include=['int64']) # 要搜尋的資料型態 int float
coverted_int = df_int.apply(pd.to_numeric,downcast='unsigned')
print(mean_usage(df_int),mean_usage(coverted_int)) #降低記憶體使用

0.00 MB 0.00 MB

In [19]:
optimuzed = df.copy()

optimuzed[coverted_int.columns] = coverted_int #優化
print(mean_usage(df))
print(mean_usage(optimuzed))

0.01 MB
0.01 MB

In [20]:
dow = df.RH
dow

0     76
1     72
2     70
3     70
4     75
5     70
6     74
7     75
8     71
9     69
10    72
11    77
Name: RH, dtype: int64

In [24]:
dow_cat = dow.astype('category') # 將重複(string object)的指定到同一個記憶體位址 降低記憶體使用
dow_cat

0     76
1     72
2     70
3     70
4     75
5     70
6     74
7     75
8     71
9     69
10    72
11    77
Name: RH, dtype: category
Categories (8, int64): [69, 70, 71, 72, 74, 75, 76, 77]

In [25]:
dow_cat.cat.codes

0     6
1     3
2     1
3     1
4     5
5     1
6     4
7     5
8     2
9     0
10    3
11    7
dtype: int8

In [26]:
print(mean_usage(dow))
print(mean_usage(dow_cat))

0.00 MB
0.00 MB

In [27]:
converted_obj = pd.DataFrame()
df_obj = df.select_dtypes(include=['object'])
for col in df_obj.columns:
    num_unique_values = len(df_obj[col].unique())
    num_total_values = len(df_obj[col])
    if num_unique_values/num_total_values < 0.5: # 單一較少重複較多
        converted_obj.loc[:,col] = df_obj[col].astype('category')
    else:
        converted_obj.loc[:,col] = df_obj[col]

In [28]:
print(mean_usage(df_obj))
print(mean_usage(converted_obj))

0.01 MB
0.01 MB

In [29]:
date = df['T Max Time']
date[:5] # 標準時間格式占用記憶體較大

0    2020/1/23 12:58
1    2020/2/26 12:12
2    2020/3/26 13:47
3    2020/4/19 12:57
4    2020/5/10 12:16
Name: T Max Time, dtype: object

In [30]:
print(mean_usage(date))

0.00 MB